# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

platform :ios do
    projectPath = "eSageApp/eSageApp.xcodeproj"
    teamId = "LQQPYJBXWS"
    bundleId = "hiennguyen.eSageApp"
    plistPath = "eSageApp/App/SupportingFiles/Info.plist"
    envName = ""
    outputName = "eSageApp.ipa"
  
    scheme = ""
    environment = ""
    configuration = ""
    exportMethod = ""
    provisioningProfile = ""
    tag_name = ""
    codeSign = "iPhone Distribution"
  
    GITHUB_REPO_NAME = "nguyenduchien/eSageApp"
    VERSION_PATTERN = /((\d+\.)(\d+\.)(\*|\d+))/


    #DEPLOYGATE // Can define at Environment Variables on CI
    DEPLOYGATE_API_KEY = "73b55308-9c2d-4ba8-99d0-6f432445f41f"
    DEPLOYGATE_USER = "at-hiennguyen2"
    
    #FIREBASE
    FIREBASE_CLI_PATH = '/usr/local/bin/firebase' #'./node_modules/.bin/firebase'

    #SLACK
    SLACK_WEBHOOK_URL_DEV = 'https://hooks.slack.com/services/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'
    SLACK_CHANNEL_DEV = 'app-distribution'

    lane :get_certs_and_provisionings do
        match(type: "development", readonly: true)
        match(type: "adhoc", readonly: true)
        match(type: "appstore", readonly: true)
    end

    lane :update_certs_and_provisionings do
        match(type: "development", force_for_new_devices: true)
        match(type: "adhoc", force_for_new_devices: true)
        match(type: "appstore", force_for_new_devices: true)
        
    end

    private_lane :build do
        disable_automatic_code_signing(path: projectPath)
        gym(
            scheme: scheme,
            export_team_id: teamId,
            export_method: exportMethod,
            configuration: configuration,
            output_name: outputName,
            clean: true,
            xcargs: 'CODE_SIGN_IDENTITY="' + codeSign + '"',
            export_options: {
                manageAppVersionAndBuildNumber: false,
                provisioningProfiles: {
                    bundleId => provisioningProfile
                }
            }
        )
        # upload_deploygate
    end

    private_lane :update_provisioning_specifier do
        update_provisioning_profile_specifier(
          new_specifier: provisioningProfile,
          xcodeproj: projectPath,
          configuration: configuration,
          target: "eSageApp"
        )
    end

      private_lane :update_build_version do
          buildtime = Time.now.strftime("%m-%d %H-%M")
      
          appVersion = get_version_number(
            xcodeproj: projectPath,
            configuration: configuration,
            target: "eSageApp"
          )
          versions = appVersion.split(".")
          versions.pop()
          fixedVersions = versions.push(buildtime)
          fixedBuildVersion = fixedVersions.join(".")
      
          update_info_plist(
            xcodeproj: projectPath,
            plist_path: plistPath,
            block: lambda { |plist|
              plist["CFBundleVersion"] = fixedBuildVersion
            }
          )
      end
end